# Week2_Summary

In [3]:
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier #ML 알고리즘 의사결정 트리
from sklearn.model_selection import train_test_split #학습/테스트 데이터 분리

In [4]:
iris = load_iris()
iris_data = iris.data

iris_label = iris.target
print('iris target값:', iris_label)
print('iris target명:', iris.target_names)

iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.head()

iris target값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=11) #데이터 분리

In [6]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train, y_train) #학습 수행

pred = dt_clf.predict(X_test) #예측 수행

In [7]:
from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


accuracy_score(<b>실제 레이블 데이터 세트, 예측 레이블 데이터 세트</b>): 정확도 측정

<b>프로세스 정리</b>
- 데이터 세트 분리
- 모델 학습: ML알고리즘을 적용해 모델 학습
- 예측 수행
- 평가

## 사이킷런 기반 프레임워크
### fit(), predict()
estimator: 지도학습의 모든 알고리즘(분류(Classifier)/회귀(Regressor))을 구현한 클래스. <br>
<b>fit()</b>: 모델 학습 <br>
<b>predict()</b>: 모델 예측 <br>
*주요 모듈(p.94)

## Modul Selection
### 학습/테스트 데이터 세트 분리 - train_test_split()
train_test_split(<b>피처 데이터 세트, 레이블 데이터 세트, test_size=0.2, random_state=11</b>) <br>
- test_size: 전체 데이터 세트 중 테스트 데이터 세트의 비율(default: 0.25)
- random_state: 호출할 때 같은 학습/테스트용 데이터 세트를 생성하기 위해 주어지는 난수 발생 값(숫자 자체는 어떻게 지정해도 상관X)<br>
- suffle: 데이터를 분리하기 전 미리 섞을지 결정(default=TRUE). 데이터를 분산시켜 더 효율적인 학습 데이터 세트를 만든다.

## 교차 검증
<b>과적합(Overfitting)</b>: 모델이 학습 데이터에만 과도하게 최적화되어 실제 예측을 다른 데이터로 수행할 경우 성능이 떨어질 수 있음 <br>
이러한 데이터 편중을 막기 위해 별도의 학습 데이터 세트와 검정 데이터 세트에서 학습, 평가를 수행 <br>

cf) Train(Train, Validation), Test

### K 폴드
<b>Kfold(n splits=k)</b> <p>
K개의 데이터 폴드 세트를 만들어서 K번만큼 각 폴드 세트에 학습과 검증 평가를 반복적으로 수행 <br>
학습 데이터 세트와 검증 데이터 세트를 <u>점진적으로 변경</u>하면서 마지막까지 학습과 검증을 수행<br>
K개의 예측 평가를 구했으면 이를 평균해서 K폴드 평가 결과로 반영한다.

In [12]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)

kfold = KFold(n_splits=5)
cv_accuracy = [] #정확도를 담을 list 생성
print('붓꽃 데이터 세트 크기:',features.shape[0])

붓꽃 데이터 세트 크기: 150


In [15]:
n_iter = 0

for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    #학습, 예측
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter += 1
    
    #반복마다 정확도 측정
    accuracy = np.round(accuracy_score(y_test, pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'.format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    
    print('\n## 평균 검증 정확도:', np.mean(cv_accuracy)) 


#1 교차 검증 정확도 :1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

## 평균 검증 정확도: 0.9166666666666666

#2 교차 검증 정확도 :0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

## 평균 검증 정확도: 0.9238142857142858

#3 교차 검증 정확도 :0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

## 평균 검증 정확도: 0.916675

#4 교차 검증 정확도 :0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

## 평균 검증 정확도: 0.9185222222222222

#5 교차 검증 정확도 :0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

## 평균 검증 정확도: 0.9


### Stratified K 폴드
불균형한 분포도(특정 레이블 값의 분포가 한 쪽으로 치우침)를 가진 레이블 데이터 집합을 위한 K폴드 방식. <br>
K 폴드로 분할된 레이블 데이터 세트가 전체 레이블 값의 분포도를 반영하지 못하는 문제를 해결함 <p>
    cf) K 폴드와 달리 split()메서드에 인자로 <b>피처 데이터 세트, 레이블 데이터 세트</b>도 반드시 필요함

In [20]:
import pandas as pd

iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

<b>kfold.split(X)</b>는 폴드 세트를 반복할 때마다 달라지는 학습/테스트 용 데이터 로우 인덱스 번호 반환

In [21]:
kfold = KFold(n_splits=3)

n_iter =0
for train_index, test_index  in kfold.split(iris_df):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 2    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 1    50
0    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [22]:
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter += 1
    label_train= iris_df['label'].iloc[train_index]
    label_test= iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 2    34
1    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
0    17
2    16
Name: label, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 1    34
2    33
0    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
0    17
1    16
Name: label, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 0    34
2    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    17
1    17
0    16
Name: label, dtype: int64


### cross_val_score(); 간편한 교차 검증

①폴드 세트 설정<br> ②for 루프에서 반복으로 학습/데이터 데이터 인덱스 추출<br> ③반복적으로 학습과 예측 수행<br>을 한번에 수행하는 API <p></p>
cross_val_score(<b>estimator, X, y=None, scoring=None, cv=None,</b> n_jobs=1, verbose=0, fit_params=None, pre_dispatch=2*n_jobs') <br>
- estimator: 분류 알고리즘 클래스(Clssifier, Regressor)
- X: 피처 데이터 세트
- y: 레이블 데이터 세트
- scoring: 예측 성능 평가 지표 기술(ex. accuracy)
- cv: 교차 검증 폴드 수
- 반환 값: cv로 지정된 횟수만큼 scoring 파라미터로 지정된 성능 지표 측정값을 배열 형태로 반환. 일반적으로 평균하여 평가 수치로 사용

cf) cross_validate(); 여러 개의 평가 지표 반환, 성능 평가 지표와 수행 시간도 같이 제공

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score , cross_validate
from sklearn.datasets import load_iris

iris_data = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data = iris_data.data
lable = iris_data.target

scores = cross_val_score(dt_clf, data, lable, scoring='accuracy', cv=3)
print('교차 검증별 정확도:',np.round(scores, 4))
print('평균 검증 정확도:', np.round(np.mean(scores), 4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667


### GridSerchCV ; 교차 검증&파라미터 튜닝

교차 검증을 기반으로 하이퍼 파라미터의 최적 값을 찾게 해줌 <br>
순차적으로 파라미터를 테스트하여 수행시간이 상대적으로 오래 걸림<br><br>
파라미터
- estimator: classifier, regressor, pipeline
- param_grid: key+리스트 값을 가지는 딕셔너리, estimator의 튜닝을 위해 파라미터 값 지정
- scoring: 예측 성능을 측정할 평가 방법 지정
- cv: 교차 검증을 위해 분할되는 학습/테스트 세트의 개수 지정
- refit: default=TRUE, 가장 최적의 하이퍼 파라미터를 찾은 뒤 입력된 estimator 객체를 해당 파라미터로 재학습


In [27]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris_data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)

dtree = DecisionTreeClassifier()

parameters = {'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]}

In [30]:
import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(X_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', \
           'split0_test_score', 'split1_test_score', 'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

칼럼별 의미<br>
- params: 수행할 때마다 적용된 개별 하이퍼 파라미터값
- rank_test_score: 하이퍼 파라미터별로 성능이 좋은 score 순위
- mean_test_score: 개별 하이퍼 파라미터별로 CV의 폴딩 테스트 세트에 대해 총 수행한 평가 평균값

In [31]:
print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도: {0:.4f}'.format(grid_dtree.best_score_))

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도: 0.9750


GridSearchCV 객체의 fit()을 수행하고 난 후 최고 성능을 나타낸 하이퍼 파라미터의 값(best_parms), 그 때의 평과 결과 값(best_score)이 속성에 기록됨

# 데이터 전처리
사이킷런의 머신러닝 알고리즘은 문자열 값을 입력 값으로 허용하지 않음. 모든 문자열 값은 인코딩되어 숫자 형으로 변환해야 함. <br>

## 데이터 인코딩
### 레이블 인코딩(Lable Encoding)
카테고리 피처를 코드형 숫자 값으로 변환하는 것. <br>
cf) 01, 02와 같은 코드 값도 문자열이므로 1, 2 같은 숫자형 값으로 변환<br><br>

<b>LabelEncoder</b>를 객체로 생성 후 <b>fit()</b>과 <b>transform()</b>을 호출해 인코딩 수행<br>
- classes_: 속성값으로 인코딩 클래스 확인
- inverse_transform(): 인코딩된 값을 다시 디코딩

cf) 숫자 값으로 변환되며 몇몇 ML 알고리즘에 적용될 경우, 숫자의 특성이 작용해 예측 성능이 떨어질 수 있음<br>
따라서 레이블 인코딩은 선형회귀와 같은 ML알고리즘에 적용되지 않아야 함

In [37]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
lables = encoder.transform(items)

print('인코딩 변환값:', lables)
print('인코딩 클래스:',encoder.classes_)
print('디코딩 원본 값:',encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

인코딩 변환값: [0 1 4 5 3 3 2 2]
인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']
디코딩 원본 값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 원-핫 인코딩(One-Hot Encoding)
피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 1을 표시하고, 나머지 칼럼에는 0을 표시<br><br>

<b>OneHotEncoder</b>로 변환 가능<br>
※변환하기 전에 모든 문자열 값이 숫자형 값으로 변환되어야 하고, 입력 값으로 2차원 데이터가 필요

In [41]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1) #2차원 데이터로 변환

#원핫인코딩
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


### 판다스의 원핫인코딩
<b>get_dummies</b><br>
문자열 카테고리 값을 숫자 형으로 변환할 필요 없이 바로 변환 가능

In [42]:
import pandas as pd

df = pd.DataFrame({'item':['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서'] })
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자렌지  item_컴퓨터
0        1         0        0         0          0         0
1        0         1        0         0          0         0
2        0         0        0         0          1         0
3        0         0        0         0          0         1
4        0         0        0         1          0         0
5        0         0        0         1          0         0
6        0         0        1         0          0         0
7        0         0        1         0          0         0

## 피처 스케일링과 정규화
피처 스케일링(feature scaling): 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업<br><br>
<b>표준화(Standardization)</b><br>
N(0, 1)을 따르는 값으로 변환<br><br>

<b>정규화(Normalization)</b><br>
개별 데이터의 크기를 모두 똑같은 단위로 변경<br>
x_new = (x-min(x))/max(x)-min(x)

### StandardScaler
표준화를 지원하는 클래스<br><br>
<b>fit()</b>과 <b>transform()</b> 매서드에 변환 대상 데이터를 입력하고 호출 <br>
이 때 transform을 호출하여 스케일 변환된 데이터 세트는 넘파이의 ndarray

In [43]:
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\nfeature 들의 분산 값')
print(iris_df.var())

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [44]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\nfeature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


### MinMaxScaler
데이터 값을 0과 1사이의 범위 값으로 변환(음수는 -1에서 1로 변환)<br>
데이터의 분포가 가우시안 분포가 아닐 경우 적용할 수 있음

In [45]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

iris_df_scaled = pd.DataFrame(data=iris_scaled, columns=iris.feature_names)

print('feature들의 최소 값')
print(iris_df_scaled.min())

print('\nfeature들의 최대 값')
print(iris_df_scaled.max())

feature들의 최소 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최대 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


In [23]:
dt_clf = DecisionTreeClassifier(random_state=156)

skfold = StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

for train_index, test_index  in skfold.split(features, label):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]

    dt_clf.fit(X_train , y_train)    
    pred = dt_clf.predict(X_test)

    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred), 4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('\n#{0} 교차 검증 정확도 :{1}, 학습 데이터 크기: {2}, 검증 데이터 크기: {3}'
          .format(n_iter, accuracy, train_size, test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)
    
print('\n## 교차 검증별 정확도:', np.round(cv_accuracy, 4))
print('## 평균 검증 정확도:', np.mean(cv_accuracy)) 


#1 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]

#2 교차 검증 정확도 :0.94, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]

#3 교차 검증 정확도 :0.98, 학습 데이터 크기: 100, 검증 데이터 크기: 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]

## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도: 0.9666666666666667


### train/test data 스케일링 변환 시 유의점
- fit(): 데이터 변환을 위한 기준 정보 설정 적용
- transform(): 설정된 정보를 이용해 데이터 변환
- fit_transform(): 둘을 한번에 적용
<br>
학습 데이터 세트로 fit(), transform()을 적용 후 테스트 데이터 세트로는 fit()을 수행하지 않아야 함<br>
테스트 데이터 세트를 다시 스케일링한다면 학습 데이터와 스케일링 기준 정보가 서로 달라지기 때문에 올바른 예측 결과를 도출하지 못할 수 있음<br><br>

- 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
- 혹은 테스트 데이터 변환 시 fit(), fit_transform()을 적용하지 않고 학습 데이터로 fit()된 Scaler객체를 이용해 transform()으로 변환