## [파이썬 머신러닝 완벽 가이드] 01. 파이썬 기반의 머신러닝과 생태계 이해

01. 머신러닝의 개념

머신러닝: 애플리케이션 수정하지 않고 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

지도학습, 비지도학습, 강화학습으로 나뉨

지도학습: 분류, 회귀, 추천 시스템, 시각/음성 감지/인지, 텍스트 분석, 자연어처리

비지도학습: 클러스터링, 차원 축소, 강화학습



파이썬과 R 비교: R은 통계전용 프로그램 언어, 파이썬은 다양한 영역에서 아요되는 개발 전문 프로그램 언어

딥러인 프레임워크인 텐서플로, 케라스, 파이토치 등에서 파이썬 우선 정책으로 파이썬을 지원함





02. 파이썬 머신러닝 생태계를 구성하는 주요 패키지

-머신러닝 패키지: scikit-learn

-행렬/선형대수/통계 패키지: numpy, scipy

-데이터 핸들링: 판다스. 2차원 데이터 처리에 특화

-시각화: matplotlib, seaborn(matplotlib api를 이용해 더 함축적으로 만든 라이브러리)

-Interactvie Python틀인 주피터 노트북 사용





03. 넘파이 numpy 개요

-파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

-루프를 사용하지 않고 대량 데이터의 배열 연산 가능하게 하므로 빠른 배열 연산 속도 보장





04. 데이터 핸들링 - 판다스

-월스트리트 금융회사의 분석 전문가가 개발한 라이브러리

-행과 열로 이뤄진 2차원 데이터를 효율적으로 가공 및 처리할 수 잇는 다양하고 훌륭한 기능 제공

-파이썬의 리스트, 컬렉션, 넘파이 등의 내부 데이터 뿐만 아니라 CSV 등의 파일을 쉽게 DataFrame으로 변경해 데이터의 가공 및 분석을 편리하게 수행할 수 있게 만들어줌

-핵심 객체는 DataFrame: 여러 개의 행과 열로 이뤄진 2차원 데이터

+) Index: 개별 데이터를 고유하게 식별하는 키값. 문자열도 가능. 고유성이 보장되어야 함.

    Series와 DataFrame 차이: Series는 칼럼이 하나, DataFrame은 칼럼이 여러 개인 데이터 구조체





## 넘파이 ndarray 개요

In [2]:
import numpy as np

In [5]:
#np.array() 사용: ndarray로 변환을 원하는 객체를 인자로 입력하면 ndarray를 반환함
#ndarray.shape는 ndarray의 차원과 크기를 튜플 형태로 나타냄
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)

array2 = np.array([[1, 2, 3],
                 [2, 3, 4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [6]:
#각 array의 차원을 ndarray.dim을 이용해 확인
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [8]:
#ndarray의 데이터 타입
#한 개의 ndarray 객체에 int와 float가 함께 있을 수 없음
list1 = [1 ,2, 3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [10]:
#ndarray 내 데이터값의 타입 변경 astype() 메서드
#float->int 메모리 절약

#int32 --> float64 --> int32
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float.astype('int32')
print(array_int2, array_int2.dtype) #소숫점 이하 모두 없어짐

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [21]:
#ndarray 편리하게 생성하기: arange, zeros, ones

#arange(): array를 range()로 표현
sequence_array = np.arange(10)
print("sequence array:\n", sequence_array)
print(sequence_array.dtype, sequence_array.shape)
print("\n")

#zeros()
zero_array = np.zeros((3,2), dtype='int32')
print("zero array:\n", zero_array)
print(zero_array.dtype, zero_array.shape)
print("\n")

#ones()
one_array = np.ones((3,2))
print("one_array:\n", one_array)
print(one_array.dtype, one_array.shape)
print("\n")

sequence array:
 [0 1 2 3 4 5 6 7 8 9]
int32 (10,)


zero array:
 [[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


one_array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)




In [23]:
#ndarray의 차원과 크기를 변경하는 reshape()
print('1차원 array->2x5 array->5x2 array')

array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(5,2)
print('array3:\n', array3)

1차원 array->2x5 array->5x2 array
array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
#reshape에 인자로 -1을 적용하면 원래 ndarray와 호환되는 새로운 shape로 변환해줌
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1. reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [25]:
#reshape(1, -1)을 이용해 리스트 자료형으로 변환
array1 = np.arange(8) #1차원 array
array3d = array1.reshape((2, 2, 2)) #3차원 array
print('arrray3d:\n', array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

arrray3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [27]:
#넘파이의 ndarray의 데이터 세트 확인하기-indexing

#단일 값 추출
#1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

#index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2] #더 이상 ndarray 타입이 아니고 ndarray 내의 데이터값을 의미
print('value:', value)
print(type(value))
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>
맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [29]:
array1[0]=9
array1[8]=0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [31]:
#다차원 ndarray에서 단일 값 추출
#1차원과 2차원의 차이: 2차원의 경우 콤마로 분리된 로우와 칼럼 위치의 인덱스를 통해 접근

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0,0])
print('(row=0, col=1) index 가리키는 값:', array2d[0,1])
print('(row=1, col=0) index 가리키는 값:', array2d[1,0])
print('(row=2, col=2) index 가리키는 값:', array2d[2,2])

#이해를 돕기 위해 row와 column으로 표현했지만 사실은 axis0=0, axis1=1이 정확한 표현
#3차원 ndarray경우는 axis 0, axis 1, axis 2 3개의 축을 가지게 됨
#axis 0이 로우방향, axis 1이 칼럼 방향

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


In [32]:
#슬라이싱
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3] #0, 1, 2 index에 있는 데이터 반환
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [33]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[1:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [34]:
#2차원 슬라이싱
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0]) #칼럼 축 한쪽에만 슬라이싱 적용하고, 다른 쪽 축에는 단일 값 인덱스를 적용


array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [35]:
#array2d[0] --> 로우 축의 첫번째 로우 ndarray를 반환
#3차원 ndarray에서 뒤에 오는 인덱스를 없애면 2차원 ndarray 반환

print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [36]:
**#팬시 인덱싱
#리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ', array3.tolist())
#(row, col) 인덱스가 (0,2), (1,2)로 적용돼 [3,6]을 반환함

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 2] => ', array4.tolist())
#((0,0), (0,1)), ((1,0), (1,1)) 인덱싱이 적용됨

array5 = array2d[[0, 1]]
print('array2d[0,1] => ', array5.tolist())
#((0, :), (1:0)) 인덱싱이 적용됨

array2d[[0,1], 2] =>  [3, 6]
array2d[[0, 1], 2] =>  [[1, 2], [4, 5]]
array2d[0,1] =>  [[1, 2, 3], [4, 5, 6]]


In [37]:
#불린 인덱싱: 조건 필터링과 검색을 동시에 할 수 있어 매우 자주 사용되는 인덱싱 방식
array1d = np.arange(start=1, stop=10)

#[] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d>5] #ndarray의 인덱스를 지정하는 [] 내에 조건문을 그대로 기재하기만 하면 됨
print('array1d>5 불린 인덱싱 결과 값:', array3)

'''
Step1. array1d>5와 같이 ndarray의 필터링 조건을 [] 안에 기재
Step2. False값은 무시하고 True값에 해당하는 인덱스값만 저장
(True값 자제가 아닌 True값을 가진 인덱스를 저장)
Step3. 저장된 인덱스 데이터 세트로 ndarray 조회
'''

array1d>5 불린 인덱싱 결과 값: [6 7 8 9]


In [38]:
#numpy 객체에 조건식을 할당하면 어떤 일이 일어나느지 확인
array1d>5
#False, True로 이루어진 ndarray 객체 반환

array([False, False, False, False, False,  True,  True,  True,  True])

In [42]:
#행렬의 정렬 -sort() 와 argsort()
#np.sort(), ndarray.sort(), argsort()

#행렬 정렬
#np.sort()와 같이 넘파이에서 sort()를 호출. 원 행렬 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
#ndarray.sort()와 같이 행렬 자체에서 sort()를 호출. 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None

org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)

#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬', org_array)


원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬 [1 3 5 9]


In [44]:
#기본적으로 오름차순. 내림차순 적용하기 위해서는 np.sort()[::-1]

sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [45]:
#행렬이 2차원 이상일 경우

array2d = np.array([[8,12], 
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0) #로우 방향으로 정렬
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


In [47]:
#정렬된 행렬의 인덱스 반환하기: np.argsort()

org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [48]:
'''
넘파이의 ndarray는 RDBMS의 TABLE칼럼이나 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없음
실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야 함
'''
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 94, 98, 88])

sort_indices_asc = np.argsort(score_array) #정렬하기
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc) #원본행렬의 인덱스
print('성적 오름차순으로 name_arry의 이름 출력:', name_array[sort_indices_asc]) #정렬 시 이름 출력

성적 오름차순 정렬 시 score_array의 인덱스: [0 4 2 1 3]
성적 오름차순으로 name_arry의 이름 출력: ['John' 'Samuel' 'Sarah' 'Mike' 'Kate']


In [49]:
#선형대수 연산 - 행렬 내적과 전치 행렬 구하기

#행렬 내적(행렬 곱): np.dot()

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [50]:
#전치 행렬(Transpose): 원 행렬에서 행과 열의 위치를 교환한 원소로 구성한 행렬
A = np.array([[1,2], [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치행렬:\n', transpose_mat)

A의 전치행렬:
 [[1 3]
 [2 4]]


## 데이터 핸들링 - 판다스

In [53]:
import pandas as pd

titanic_df = pd.read_csv('C:\\Users\\user\\Data_Handling\\titanic_train.csv') #파일명 인자로 들어온 파일 로딩해 DataFrame 객체로 반환함
print('titanic 변수 type:', type(titanic_df))
titanic_df.head(3)

#모든 DF 내 데이터는 생성되는 순간 고유의 index값을 가지게 됨


titanic 변수 type: <class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [54]:
#DF의 행과 열 크기 알아보기
print('DataFrame 크기: ', titanic_df.shape)

DataFrame 크기:  (891, 12)


In [55]:
titanic_df.info()

'''
RangeIndex는 DF index의 범위 나타냄. 전체 row 수를 알 수 있음.
전체 데이터는 891개 row. Column 수는 12개.

Dtype: 칼럼별 데이터타입. object=문자열

Non-Null Count: 몇 개의 데이터가 non-null인지. ex. Age column은 714 non-null, 891-714 null

dtypes: 요약
'''

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [56]:
'''
칼럼별 숫자형 데이터갑스의 n-percentile 분포도, 평균값, 최댓값, 최솟값을 나타냄
오직 숫자형 칼럼의 분포도만 조사.object 타입은 출력에서 제외.

회귀에서 결정 값이 정규 분포를 이루지 않고 특정 값으로 왜곡돼 있는 경우,
또는 데이터값에 이상치가 많을을 경우 예측 성능이 저하됨
개략적인 수준의 분포도 확인할 수 있어 용이
'''

titanic_df.describe()
'''
count: not-null인 데이터 건수

PassengerID 칼럼은 승객ID 식별 칼럼으로 분석을 위한 의미있는 속성이 아님.

카테고리 칼럼: 특정 범주에 속하는 값을 코드화
Survived의 경우 0,1로 이루어진 숫자형 카테고리 칼럼
Pclass의 경우 1, 2, 3으로 이루어진 숫자형 카테고리 칼럼
'''

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [58]:
#Pclass
value_counts = titanic_df['Pclass'].value_counts() #해당 칼럼값의 유혐과 건수 확인. 데이터 분포도 확인에 유용.
print(value_counts)

3    491
1    216
2    184
Name: Pclass, dtype: int64


In [59]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>


In [60]:
titanic_pclass.head()

0    3
1    1
2    3
3    1
4    3
Name: Pclass, dtype: int64

In [62]:
'''인덱스는 단순하 순차 값과 같은 의미없는 식별자만 할당하는 것이 아니라 
고유성이 보장된다면 의미있는 데이터값 할당도 가능함
인덱스는 문자열도 가능함
모든 인덱스는 고유성이 보장되어야 함
'''

'인덱스는 단순하 순차 값과 같은 의미없는 식별자만 할당하는 것이 아니라 \n고유성이 보장된다면 의미있는 데이터값 할당도 가능함\n인덱스는 문자열도 가능함\n모든 인덱스는 고유성이 보장되어야 함\n'

In [63]:
#DataFrame과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환

In [65]:
#1차원 형태의 리스트와 ㄴ머파이 ndarray부터 DF로 변환

import numpy as np

col_name1 = ['col1']
list1 = [1, 2, 3]
array1 = np.array(list1)
print('array1 shape:', array1.shape)

#리스트 이용해 DataFrame 생성
df_list1 = pd.DataFrame(list1, columns=col_name1)
print('1차원 리스트로 만든 DataFrame:\n', df_list1)

#넘파이 ndarray를 이용해 DataFrame 생성
df_array1 = pd.DataFrame(array1, columns=col_name1)
print('1차원 ndarray로 만든 DataFrame:\n', df_array1)



array1 shape: (3,)
1차원 리스트로 만든 DataFrame:
    col1
0     1
1     2
2     3
1차원 ndarray로 만든 DataFrame:
    col1
0     1
1     2
2     3


In [66]:
#2차원 형태의 데이터를 기반으로 DF 생성

#3개의 칼럼명이 필요함
col_name2 = ['col1', 'col2', 'col3']

#2행3열 형태의 리스트와 ndarray 생성한 뒤 이를 DF으로 변환
list2 = [[1, 2, 3], [11, 12, 13]]
array2 = np.array(list2)
print('array2 shape:', array2.shape)

df_list2 = pd.DataFrame(list2, columns=col_name2)
print('2차원 리스트로 만든 DataFrame:\n', df_list2)

df_array2 = pd.DataFrame(array2, columns=col_name2)
print('2차원 ndarray로 만든 DataFrame:\n', df_array2)

array2 shape: array2.shape
2차원 리스트로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13
2차원 ndarray로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    12    13


In [67]:
#딕셔너리를 DF로 변환: Key는 칼럼명, Value는 키에 해당하는 칼럼 데이터
#키는 문자열, 값은 리스트 또는 ndarray 형태

dict = {'col1':[1,11], 'col2':[2, 22], 'col3':[3, 33]}
df_dict = pd.DataFrame(dict)
print('딕셔너리로 만든 DataFrame:\n', df_dict) #키값은 칼럼명, 각 벨류는 각 칼럼 데이터

딕셔너리로 만든 DataFrame:
    col1  col2  col3
0     1     2     3
1    11    22    33


In [68]:
#DataFrame to ndarray" 객체의 values 이용
array3 = df_dict.values
print('df_dict.values 타입:', type(array3), 'df_dict.values shape:', array3.shape)
print(array3)

df_dict.values 타입: <class 'numpy.ndarray'> df_dict.values shape: (2, 3)
[[ 1  2  3]
 [11 22 33]]


In [72]:
#DF -> 리스트: values로 얻은 ndarray에 tolist() 호출
list3 = df_dict.values.tolist()
print('df_dict.values.tolist() 타입:', type(list3))
print(list3)

#DF -> 딕셔너리: DF 객체의 to_dict()
dict3 = df_dict.to_dict('list')
print('\n df_dict.to_dict() 타입:', type(dict3))
print(dict3)

df_dict.values.tolist() 타입: <class 'list'>
[[1, 2, 3], [11, 22, 33]]

 df_dict.to_dict() 타입: <class 'dict'>
{'col1': [1, 11], 'col2': [2, 22], 'col3': [3, 33]}


In [73]:
#DF의 칼럼 데이터 세트 생성과 수정

titanic_df['Age_0']=0 #새로운 칼럼 추가, 일괄적으로 0값을 할당
titanic_df.head(3)

#새로운 칼럼명 'Age_0'으로 모든 데이터값이 0으로 할당된 Series가 기존 DataFrame에 추가됨을 알 수 있음
#넘파이의 ndarray에 상숫값을 할당할 때 모든 ndarray값에 일괄 적용됨과 동일

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  
0      0         A/5 21171   7.2500   NaN        S      0  
1      0          PC 17599  71.2833   C85        C      0  
2      0  STON/O2. 3101282   7.9250   NaN        S      0

In [74]:
#기존 칼럼 Series의 데이터를 이용하여 새로운 칼럼 Series를 만듦
titanic_df['Age_by_10']=titanic_df['Age']*10
titanic_df['Family_No']=titanic_df['SibSp']+titanic_df['Parch']+1
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0      220.0   
1      0          PC 17599  71.2833   C85        C      0      380.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0      260.0   

   Family_No  
0          2  
1          2  
2          1

In [76]:
#기존 칼럼값 일괄적으로 업데이트
titanic_df['Age_by_10']=titanic_df['Age_by_10']*10
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_0  Age_by_10  \
0      0         A/5 21171   7.2500   NaN        S      0     2200.0   
1      0          PC 17599  71.2833   C85        C      0     3800.0   
2      0  STON/O2. 3101282   7.9250   NaN        S      0     2600.0   

   Family_No  Age_by_100  
0          2      2200.0  
1          2      3800.0  
2          1      2600.0

In [78]:
#DF 데이터 삭제
titanic_drop_df = titanic_df.drop(labels='Age_0', axis=1, inplace=False)
#label에 원하는 칼럼명, axis=1 -> 지정된 칼럼 드롭
titanic_drop_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_10  Family_No  \
0      0         A/5 21171   7.2500   NaN        S     2200.0          2   
1      0          PC 17599  71.2833   C85        C     3800.0          2   
2      0  STON/O2. 3101282   7.9250   NaN        S     2600.0          1   

   Age_by_100  
0      2200.0  
1      3800.0  
2      2600.0

In [79]:
#DF 데이터 자체의 데이터 삭제
drop_result = titanic_df.drop(['Age_0', 'Age_by_10', 'Family_No'], axis=1, inplace=True)
print(' inplace=True로 drop후 반환된 값: ', drop_result)
titanic_df.head(3)

 inplace=True로 drop후 반환된 값:  None


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_100  
0      0         A/5 21171   7.2500   NaN        S      2200.0  
1      0          PC 17599  71.2833   C85        C      3800.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      2600.0

In [81]:
print(drop_result)

None


In [84]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Age_by_100  
0      0         A/5 21171   7.2500   NaN        S      2200.0  
1      0          PC 17599  71.2833   C85        C      3800.0  
2      0  STON/O2. 3101282   7.9250   NaN        S      2600.0  
3      0            113803  53.1000  C123        S      3500.0  
4      0            373450   8.0500   NaN        S      3500.0

In [86]:
#axis=0으로 설정해 index 0, 1, 2(맨 앞 3개의 데이터) 로우를 삭제
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', 15)
print('#### before axis 0 drop ####')
print(titanic_df.head(3))
titanic_df.drop([0, 1, 2], axis=0, inplace=True)

print('#### after axis 0 drop ####')
print(titanic_df.head(3)) #삭제 후 head(3)으로 확인한 맨 앞 3개 데이터의 인덱스는 3, 4, 5

#11/03

#### before axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch          Ticket     Fare Cabin Embarked  Age_by_100
0            1         0       3  Braund, Mr....    male  22.0      1      0       A/5 21171   7.2500   NaN        S      2200.0
1            2         1       1  Cumings, Mr...  female  38.0      1      0        PC 17599  71.2833   C85        C      3800.0
2            3         1       3  Heikkinen, ...  female  26.0      0      0  STON/O2. 31...   7.9250   NaN        S      2600.0
#### after axis 0 drop ####
   PassengerId  Survived  Pclass            Name     Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  Age_by_100
3            4         1       1  Futrelle, M...  female  35.0      1      0  113803  53.1000  C123        S      3500.0
4            5         0       3  Allen, Mr. ...    male  35.0      0      0  373450   8.0500   NaN        S      3500.0
5            6         0       3  Moran, Mr. ...    male   NaN  

In [3]:
#Index 객체
#Dataframe, Series의 레코드를 고유하게 식별하는 개체
#DataFrame.index, Series-index

import pandas as pd

#원본 파일 다시 로딩
titanic_df = pd.read_csv('C:\\Users\\user\\Data_Handling\\titanic_train.csv')
#index 객체 추출
indexes = titanic_df.index
print(indexes)
#index 객체를 실제 값 array로 변환
print('Index 객체 arrayrkqt:\n', indexes.values)

RangeIndex(start=0, stop=891, step=1)
Index 객체 arrayrkqt:
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 

In [4]:
#index 객체는 식별성 데이터를 1차원 array로 가지고 있음. 
#또한 ndarray와 유사하게 단일 값 반환 및 슬라이싱도 가능

print(type(indexes.values))
print(indexes.values.shape)
print(indexes[:5].values)
print(indexes.values[:5])
print(indexes[6])

#한 번 만들어진 객체는 함부로 변경할 수 없음

<class 'numpy.ndarray'>
(891,)
[0 1 2 3 4]
[0 1 2 3 4]
6


In [16]:
#Series 객체는 index 객체를 포함하지만 series 객체에 연산 함수를 적용할 때 index는 연산에서 제외됨
#index는 오직 식별용으로만 사용됨

series_fair = titanic_df['Fare']

print(series_fair.head())
print('Fair Series max값:', series_fair.max())
print('Fair Series sum값:', series_fair.sum())
print('sum() Fair Series:', sum(series_fair))
print('Fair Series +3:\n', (series_fair+3).head(3))

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64
Fair Series max값: 512.3292
Fair Series sum값: 28693.9493
sum() Fair Series: 28693.949299999967
Fair Series +3:
 0    10.2500
1    74.2833
2    10.9250
Name: Fare, dtype: float64


In [17]:
#reset_index()
#새롭게 인덱스를 연속 숫자 형으로 할당하며 기존 인덱스는 index라는 새로운 칼럼 명으로 추가함
titanic_reset_df = titanic_df.reset_index(inplace=False)
titanic_reset_df.head(3)

#index가 연속된 int 숫자형 데이터가 아닐 경우에 다시 이를 연속 int 숫자형 데이터로 만들 때 주로 사용
#index칼럼이 추가되므로 더 이상 시리즈가 아닌 데이터프레임이 반환됨

index  PassengerId  Survived  Pclass  \
0      0            1         0       3   
1      1            2         1       1   
2      2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [19]:
print('### before reset_index ###')
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)
print('value_counts 객체 변수 타입:', type(value_counts))
new_value_counts = value_counts.reset_index(inplace=False)

print('### After reset_index ###')
print(new_value_counts)
print('new_value_counts 객체 변수 타입:', type(new_value_counts))

### before reset_index ###
3    491
1    216
2    184
Name: Pclass, dtype: int64
value_counts 객체 변수 타입: <class 'pandas.core.series.Series'>
### After reset_index ###
   index  Pclass
0      3     491
1      1     216
2      2     184
new_value_counts 객체 변수 타입: <class 'pandas.core.frame.DataFrame'>


In [21]:
#데이터 셀렉션 및 필터링
#넘파이: [] 연산자 내 단일 값 추출, 슬라이싱, 팬시 인덱싱, 불린 인덱싱을 통해 데이터를 추출
#판다스: ix[], iloc[], loc[] 연산자를 통해 동일한 작업 수행

#판다스[]와 넘파이[] 차이?
#데이터프레임 뒤에 있는 []는 칼럼만 지정할 수 있는 칼럼 지정 연산자로 이해

print('단일 칼럼 데이터 추출:\n', titanic_df['Pclass'].head(3))
print('\n여러 칼럼의 데이터 추출:\n', titanic_df[['Survived', 'Pclass']].head(3))
print('[] 안에 숫자 index는 KeyError 오류 발생:\n', titanic_df[0])



단일 칼럼 데이터 추출:
 0    3
1    1
2    3
Name: Pclass, dtype: int64

여러 칼럼의 데이터 추출:
    Survived  Pclass
0         0       3
1         1       1
2         1       3


KeyError: 0

In [24]:
#데이터프레임 [] 내에 숫자값을 입력할 경우 오류가 발생. 판다스의 인덱스 형태로 변환 가능한 표현식은 []내에 입력 가능
#titanic_df의 처음 2개 데이터를 추출하고자 titanic_df[0:2]와 같은 슬라이싱을 이용하면 정확히 원하는 결과를 반환함
titanic_df[0:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [23]:
#불린 인덱싱 표현도 가능
titanic_df[titanic_df['Pclass']==3].head(3)

PassengerId  Survived  Pclass                      Name     Sex   Age  \
0            1         0       3   Braund, Mr. Owen Harris    male  22.0   
2            3         1       3    Heikkinen, Miss. Laina  female  26.0   
4            5         0       3  Allen, Mr. William Henry    male  35.0   

   SibSp  Parch            Ticket   Fare Cabin Embarked  
0      1      0         A/5 21171  7.250   NaN        S  
2      0      0  STON/O2. 3101282  7.925   NaN        S  
4      0      0            373450  8.050   NaN        S

In [25]:
#ix[] 연산자 사라지고 칼럼 명칭 기반 인덱싱 연산자인 loc[]와 칼럼 위치 기반 인덱싱 연산자인 iloc[]가 새롭게 만들어짐

data = {'Name': ['Chulmin', 'Eunkyung', 'Jinwoong', 'Soobeom'], 
        'Year': [2011, 2016, 2015, 2015], 
        'Gender': ['Male', "Female", 'Male', 'Male']}
data_df = pd.DataFrame(data, index=['one', 'two', 'three', 'four'])
data_df

Name  Year  Gender
one     Chulmin  2011    Male
two    Eunkyung  2016  Female
three  Jinwoong  2015    Male
four    Soobeom  2015    Male

In [26]:
#위치 기반 인덱싱

data_df.iloc[0, 0]
#위치 인덱싱이 아닌 명칭을 입력하면 오류 발생
#문자열 인덱스를 행 위치에 입력해도 오류 발생

'Chulmin'

In [28]:
#명칭 기반 인덱싱

data_df.loc['one', 'Name']

'Chulmin'

In [29]:
#불린 인덱싱

titanic_df = pd.read_csv('C:\\Users\\user\\Data_Handling\\titanic_train.csv')
titanic_boolean = titanic_df[titanic_df['Age']>60]
print(type(titanic_boolean))
titanic_boolean

<class 'pandas.core.frame.DataFrame'>


PassengerId  Survived  Pclass                                       Name  \
33            34         0       2                      Wheadon, Mr. Edward H   
54            55         0       1             Ostby, Mr. Engelhart Cornelius   
96            97         0       1                  Goldschmidt, Mr. George B   
116          117         0       3                       Connors, Mr. Patrick   
170          171         0       1                  Van der hoef, Mr. Wyckoff   
252          253         0       1                  Stead, Mr. William Thomas   
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
280          281         0       3                           Duane, Mr. Frank   
326          327         0       3                  Nysveen, Mr. Johan Hansen   
438          439         0       1                          Fortune, Mr. Mark   
456          457         0       1                  Millet, Mr. Francis Davis   
483          484         1       3                     Turkula, Mrs. (Hedwig)   
493          494         0       1                    Artagaveytia, Mr. Ramon   
545          546         0       1               Nicholson, Mr. Arthur Ernest   
555          556         0       1                         Wright, Mr. George   
570          571         1       2                         Harris, Mr. George   
625          626         0       1                      Sutton, Mr. Frederick   
630          631         1       1       Barkworth, Mr. Algernon Henry Wilson   
672          673         0       2                Mitchell, Mr. Henry Michael   
745          746         0       1               Crosby, Capt. Edward Gifford   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   
851          852         0       3                        Svensson, Mr. Johan   

        Sex   Age  SibSp  Parch       Ticket      Fare        Cabin Embarked  
33     male  66.0      0      0   C.A. 24579   10.5000          NaN        S  
54     male  65.0      0      1       113509   61.9792          B30        C  
96     male  71.0      0      0     PC 17754   34.6542           A5        C  
116    male  70.5      0      0       370369    7.7500          NaN        Q  
170    male  61.0      0      0       111240   33.5000          B19        S  
252    male  62.0      0      0       113514   26.5500          C87        S  
275  female  63.0      1      0        13502   77.9583           D7        S  
280    male  65.0      0      0       336439    7.7500          NaN        Q  
326    male  61.0      0      0       345364    6.2375          NaN        S  
438    male  64.0      1      4        19950  263.0000  C23 C25 C27        S  
456    male  65.0      0      0        13509   26.5500          E38        S  
483  female  63.0      0      0         4134    9.5875          NaN        S  
493    male  71.0      0      0     PC 17609   49.5042          NaN        C  
545    male  64.0      0      0          693   26.0000          NaN        S  
555    male  62.0      0      0       113807   26.5500          NaN        S  
570    male  62.0      0      0  S.W./PP 752   10.5000          NaN        S  
625    male  61.0      0      0        36963   32.3208          D50        S  
630    male  80.0      0      0        27042   30.0000          A23        S  
672    male  70.0      0      0   C.A. 24580   10.5000          NaN        S  
745    male  70.0      1      1    WE/P 5735   71.0000          B22        S  
829  female  62.0      0      0       113572   80.0000          B28      NaN  
851    male  74.0      0      0       347060    7.7750          NaN        S

In [31]:
titanic_df[titanic_df['Age']>60][['Name', 'Age']].head()

Name   Age
33            Wheadon, Mr. Edward H  66.0
54   Ostby, Mr. Engelhart Cornelius  65.0
96        Goldschmidt, Mr. George B  71.0
116            Connors, Mr. Patrick  70.5
170       Van der hoef, Mr. Wyckoff  61.0

In [36]:
titanic_df[(titanic_df['Age']>60) & (titanic_df['Pclass']==1) & 
           (titanic_df['Sex']=='female')]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [37]:
cond1 = titanic_df['Age']>60
cond2 = titanic_df['Pclass']==1
cond3 = titanic_df['Sex']=='female'
titanic_df[cond1 & cond2 & cond3]

PassengerId  Survived  Pclass                                       Name  \
275          276         1       1          Andrews, Miss. Kornelia Theodosia   
829          830         1       1  Stone, Mrs. George Nelson (Martha Evelyn)   

        Sex   Age  SibSp  Parch  Ticket     Fare Cabin Embarked  
275  female  63.0      1      0   13502  77.9583    D7        S  
829  female  62.0      0      0  113572  80.0000   B28      NaN

In [38]:
#정렬, Aggregation 함수, GroupBy 적용
#DataFrame, Series의 정렬 - sort_values()
'''
주요 파라미터 by, ascending, inplace
by로 특정 칼럼을 입력하면 해당 칼럼으로 정렬 수행

ascending=True로 설정하면 오름차순으로 정렬, ascending=False로 설정하면 내림차순으로 정렬.
기본은 ascending=True

inplace=False로 설정하면 sort_values()를 호출한 DataFrame은 그대로 유지하며 정렬된 DataFrame을 결과로 반환함
inplace=True로 설정하면 호출한 DataFrame의 정렬 결과를 그대로 적용함
기본은 inplace=False
'''
titanic_sorted = titanic_df.sort_values(by=['Name'])
titanic_sorted.head(3)

PassengerId  Survived  Pclass                              Name     Sex  \
845          846         0       3               Abbing, Mr. Anthony    male   
746          747         0       3       Abbott, Mr. Rossmore Edward    male   
279          280         1       3  Abbott, Mrs. Stanton (Rosa Hunt)  female   

      Age  SibSp  Parch     Ticket   Fare Cabin Embarked  
845  42.0      0      0  C.A. 5547   7.55   NaN        S  
746  16.0      1      1  C.A. 2673  20.25   NaN        S  
279  35.0      1      1  C.A. 2673  20.25   NaN        S

In [39]:
titanic_sorted = titanic_df.sort_values(by=['Pclass', 'Name'], ascending=False) #내림차순으로 정렬
titanic_sorted.head(3)

PassengerId  Survived  Pclass                             Name   Sex  \
868          869         0       3      van Melkebeke, Mr. Philemon  male   
153          154         0       3  van Billiard, Mr. Austin Blyler  male   
282          283         0       3        de Pelsmaeker, Mr. Alfons  male   

      Age  SibSp  Parch    Ticket  Fare Cabin Embarked  
868   NaN      0      0    345777   9.5   NaN        S  
153  40.5      0      2  A/5. 851  14.5   NaN        S  
282  16.0      0      0    345778   9.5   NaN        S

In [40]:
#Aggregation 함수 적용

#DataFrame에서 min(), max(), sum(), count()와 같은 aggregation 함수의 적용은 RDBMS SQL의 aggregation 함수 적용과 유사함
#DF의 경우, DF에서 바로 aggregation을 호출할 경우 모든 칼럼에 해당 aggregation을 적용한다는 차이
titanic_df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [41]:
titanic_df[['Age', 'Fare']].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [42]:
#groupby() 적용
titanic_groupby = titanic_df.groupby(by='Pclass')
print(type(titanic_groupby))

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


In [43]:
titanic_groupby = titanic_df.groupby('Pclass').count()
titanic_groupby

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [46]:
#PassengerId와 Survived 칼럼에만 count()를 수행
titanic_groupby = titanic_df.groupby('Pclass')[['PassengerId', 'Survived']].count()
titanic_groupby

PassengerId  Survived
Pclass                       
1               216       216
2               184       184
3               491       491

In [47]:
#DataFrame groupby()의 경우 적용하려는 여러 개의 aggregation 함수명을 DataFrameGroupBy 객체의 agg() 내에 인자로 입력해서 사용한다
titanic_df.groupby('Pclass')['Age'].agg([max, min])

max   min
Pclass            
1       80.0  0.92
2       70.0  0.67
3       74.0  0.42

In [48]:
#agg() 내에 입력값으로 딕셔너리 형태로 aggregation이 적용될 칼럼들과 aggregation 함수를 입력합니다

agg_format = {'Age':'max', 'SibSp':'sum', 'Fare':'mean'}
titanic_df.groupby('Pclass').agg(agg_format)

Age  SibSp       Fare
Pclass                        
1       80.0     90  84.154687
2       70.0     74  20.662183
3       74.0    302  13.675550

In [49]:
#결손 데이터 처리하기
#결손 데이터는 칼럼에 값이 없는, 즉 NULL인 경우를 의미하며, 이는 넘파이의 NaN으로 표시된다
titanic_df.isna().head(3)

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0        False     False   False  False  False  False  False  False   False   
1        False     False   False  False  False  False  False  False   False   
2        False     False   False  False  False  False  False  False   False   

    Fare  Cabin  Embarked  
0  False   True     False  
1  False  False     False  
2  False   True     False

In [50]:
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [51]:
#fillna()로 결손 데이터 대체하기
titanic_df['Cabin'] = titanic_df['Cabin'].fillna('C000')
titanic_df.head(3)

#fillna()를 이용해 반환 값을 다시 받거나 inplace=True 파라미터를 fillna()에 추가해야 실제 데이터 세트 값이 변경된다는 점

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500  C000        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250  C000        S

In [53]:
#Age 칼럼값 to 평균나이, Embarked 칼럼값 to S
titanic_df['Age']= titanic_df['Age'].fillna(titanic_df['Age'].mean())
titanic_df['Embarked']=titanic_df['Embarked'].fillna('S')
titanic_df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [54]:
#apply lambda식으로 데이터 가공
#판다스는 apply함수에 lambda 식을 결합해 DataFrame이나 Series의 레코드별로 데이터를 가공하는 기능을 제공합니다

#lambda는 파이썬에서 함수 프로그래밍을 지원하기 위하여 만들어짐

def get_square(a):
    return a**2

print('3의 제곱은:', get_square(3))

3의 제곱은: 9


In [56]:
#lambda로 표현

#:의 왼쪽에 있는 x는 입력 인자를 가리키며, 오른쪽은 입력 인자의 계산식
lambda_square = lambda x: x**2
print('3의 제곱은:', lambda_square(3))

3의 제곱은: 9


In [57]:
#lambda를 이용할 때 여러 개의 값을 입력 인자로 사용해야 할 경우에는 보통 map() 함수 결합
a=[1, 2, 3]
squares = map(lambda x: x**2, a)
list(squares)

[1, 4, 9]

In [58]:
#Name 칼럼의 문자열 개수를 별도의 칼럼인 Name_len에 생성
titanic_df['Name_len']=titanic_df['Name'].apply(lambda x : len(x))
titanic_df[['Name', 'Name_len']].head(3)

Name  Name_len
0                            Braund, Mr. Owen Harris        23
1  Cumings, Mrs. John Bradley (Florence Briggs Th...        51
2                             Heikkinen, Miss. Laina        22

In [59]:
#lambda에서 if else 절을 사용해 좀 더 복잡한 가공을 함
#나아가 15세 미만이면 Child, 그렇지 않으면 Adult로 구분하는 새로운 칼럼 Child_Adult를 apply lambda를 이용해 만듦
titanic_df['Child_Adult']=titanic_df['Age'].apply(lambda x: 'Child' if x<=15 else 'Adult')
titanic_df[['Age', 'Child_Adult']].head(8)

Age Child_Adult
0  22.000000       Adult
1  38.000000       Adult
2  26.000000       Adult
3  35.000000       Adult
4  35.000000       Adult
5  29.699118       Adult
6  54.000000       Adult
7   2.000000       Child

In [60]:
#나이가 15세 이하이면 Child, 15세=60세 사이는 Adult, 61세 이상은 Elderly로 분류하는 'Age_Cat' 칼럼을 만들어 보겠습니다.
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x: 'Child' if x<= 15 else ('Adult' if x<=60 else 'Elderly'))
titanic_df['Age_cat'].value_counts()

Adult      786
Child       83
Elderly     22
Name: Age_cat, dtype: int64

In [61]:
#나이에 따라 세분화된 분류를 수행하는 함수 생성
def get_category(age):
    cat=''
    if age<=5: cat = 'Baby'
    elif age<= 12: cat = 'Child'
    elif age <= 18: cat = 'Teenager'
    elif age<= 25: cat = 'Student'
    elif age<=35: cat = 'Young Adult'
    elif age<=60: cat = 'Adult'
    else: cat = 'Elderly'
        
    return cat

#lambda 식에 위에서 생성한 get_category() 함수를 반환값으로 지정
#get_category(X)는 입력ㄱ밧으로 'Age' 칼럼 값을 받아서 해당하는 cat 반환
titanic_df['Age_cat']=titanic_df['Age'].apply(lambda x: get_category(x))
titanic_df[['Age', 'Age_cat']].head()

Age      Age_cat
0  22.0      Student
1  38.0        Adult
2  26.0  Young Adult
3  35.0  Young Adult
4  35.0  Young Adult